Controllers/DonorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DonorProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DonorProject.Controllers
{
    
    public class DonorController : Controller
    {
        private readonly ApplicationDBContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public DonorController(UserManager<IdentityUser> userManager,
                               ApplicationDBContext db)
        {
            _db = db;
            _userManager = userManager;
        }
        [BindProperty]
        public DonationRecord donationRecord { get; set; }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ViewDonationRecord()
        {
            return View();
        }

        public IActionResult ViewReceipt(int id)
        {
            donationRecord = new DonationRecord();
            donationRecord = _db.donationRecords.FirstOrDefault(u => u.dID == id);
            if (donationRecord == null)
            {
                return NotFound();
            }
            return View(donationRecord);
        }

        public IActionResult CreateEditDonationRecord(int? id)
        {
            donationRecord = new DonationRecord();
            if (id == null)
            {
                //Create New Record
                return View(donationRecord);
            }
            //Update by retriving infomation from DB
            donationRecord = _db.donationRecords.FirstOrDefault(u => u.dID == id);
            if (donationRecord == null)
            {
                return NotFound();
            }

            return View(donationRecord);
        }

        [HttpPost]
        public IActionResult CreateEditDonationRecord()
        {
            if(ModelState.IsValid)
            {
                if (donationRecord.dID == 0)
                {
                    //Create
                    donationRecord.doneBy = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    _db.donationRecords.Add(donationRecord);
                }
                else
                {
                    //Update
                    _db.donationRecords.Update(donationRecord);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            else
            {
                return View(donationRecord);
            }
        }

        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.donationRecords.ToListAsync() });
        }

        #endregion
    }
}

Views/Donor/CreateEditDonationRecord.cshtml
<!--Donor Donation Record-->
@model DonorProject.Models.DonationRecord

<h2 class="text-info">@(Model.dID!=0? "Edit":"Create")</h2>

<div class="border container" style="padding:30px">
    <form method="post">
        @if (Model.dID != 0)
        {
            <input type="hidden" asp-for="dID" />
        }
        <input type="hidden" asp-for="status" value="Not Confirmed" />
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="name">Name / Company Name</label>
            </div>
            <div class="col-6">
                <input asp-for="name" class="form-control" />
            </div>
            <span asp-validation-for="name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="nric">NRIC / Company Registration Number</label>
            </div>
            <div class="col-6">
                <input asp-for="nric" class="form-control" />
            </div>
            <span asp-validation-for="nric" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="type"></label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio1">
                    <input type="radio" asp-for="type" value="Individual" class="form-check-inline" />Individual
                </label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="type" value="Company" class="form-check-inline" />Company
                </label>
            </div>
            <span asp-validation-for="type" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="address"></label>
            </div>
            <div class="col-6">
                <input asp-for="address" class="form-control" />
            </div>
            <span asp-validation-for="address" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="contactNo"></label>
            </div>
            <div class="col-6">
                <input asp-for="contactNo" class="form-control" />
            </div>
            <span asp-validation-for="contactNo" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="taxExemption"></label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio1">
                    <input type="radio" asp-for="taxExemption" value="Yes" class="form-check-inline" />Yes
                </label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="taxExemption" value="No" class="form-check-inline" />No
                </label>
            </div>
            <span asp-validation-for="taxExemption" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="dateOfDonation"></label>
            </div>
            <div class="col-6">
                <input asp-for="dateOfDonation" class="form-control" />
            </div>
            <span asp-validation-for="dateOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="amountOfDonation"></label>
            </div>
            <div class="col-6">
                <input asp-for="amountOfDonation" class="form-control" />
            </div>
            <span asp-validation-for="amountOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="receiptNo"></label>
            </div>
            <div class="col-6">
                <input asp-for="receiptNo" class="form-control" />
            </div>
            <span asp-validation-for="receiptNo" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="dateOfReceipt"></label>
            </div>
            <div class="col-6">
                <input asp-for="dateOfReceipt" class="form-control" />
            </div>
            <span asp-validation-for="dateOfReceipt" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="modeOfDonation"></label>
            </div>
            <div class="col-2">
                <label class="form-check-label" for="radio1">
                    <input type="radio" asp-for="modeOfDonation" value="cash" class="form-check-inline" />Cash
                </label>
            </div>
            <div class="col-2">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="modeOfDonation" value="cashcard" class="form-check-inline" />CashCard
                </label>
            </div>
            <div class="col-2">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="modeOfDonation" value="mastercard" class="form-check-inline" />MasterCard
                </label>
            </div>
            <span asp-validation-for="modeOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="purposeOfDonation"></label>
            </div>
            <div class="col-6">
                <input asp-for="purposeOfDonation" class="form-control" />
            </div>
            <span asp-validation-for="purposeOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="remarks"></label>
            </div>
            <div class="col-6">
                <textarea rows="5" asp-for="remarks" class="form-control"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.dID!=0? "Update":"Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back To Home Page</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Donor/Index.cshtml
@{
    ViewData["Title"] = "Donor Home Page";
}

<div class="container row p-0 m-0">
    <div>
        Welcome to Donor Home Page
    </div>
    <div class="col-12 border p-3">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a asp-action="CreateEditDonationRecord" asp-controller="Donor" class="btn btn-info form-control text-white">
                    Add New Donation Record
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="ViewDonationRecord" asp-controller="Donor" class="btn btn-info form-control text-white">
                    View Donation Record
                </a>
            </li>
        </ul>
    </div>
</div>

Views/Donor/ViewDonationRecord.cshtml
@{
    ViewData["Title"] = "View Donation Record";
}

<div class="container row p-0 m-0">
    <div>
        View Donation Record
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style=" width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Date of Donation</th>
                    <th>Amount of Donation</th>
                    <th>Receipt Number</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/viewDonorDonation.js"></script>
}

Views/Donor/ViewReciept.cshtml
@{
    ViewData["Title"] = "View History";
}
@model DonorProject.Models.DonationRecord

<div class="container row p-0 m-0">
    <div>
        Organization Logo
        <h2>Donation Receipt</h2>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style=" width:100%">
            <tr>
                <td>Donation Amount</td>
                <td asp-for ="asd"></td>
            </tr>
            <tr>
                <td>Donated By:</td>
                <td></td>
            </tr>
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/viewReceipt.js"></script>
}