Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DonorProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;

namespace DonorProject.Controllers
{
    [Authorize]
    public class StaffController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDBContext _db;

        public StaffController(UserManager<IdentityUser> userManager,
                                SignInManager<IdentityUser> signInManager, 
                                ApplicationDBContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }
        public DonorRecord donorRecord { get; set; }
        public DonationRecord donationRecord { get; set; }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult ViewDonationRecord()
        {
            return View();
        }

        public IActionResult ViewDonorRecord()
        {
            return View();
        }

        public IActionResult CreateEditDonationRecord(int? id)
        {
            donationRecord = new DonationRecord();
            if (id == null)
            {
                //Create New Record
                return View(donationRecord);
            }
            //Update by retriving infomation from DB
            donationRecord = _db.donationRecords.FirstOrDefault(u => u.dID == id);
            if (donationRecord == null)
            {
                return NotFound();
            }

            return View(donationRecord);
        }

        [HttpPost]
        public IActionResult CreateEditDonationRecord(DonationRecord donationRecord)
        {
            if (ModelState.IsValid)
            {
                if (donationRecord.dID == 0)
                {
                    //Create
                    donationRecord.doneBy = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    _db.donationRecords.Add(donationRecord);
                }
                else
                {
                    //Update
                    _db.donationRecords.Update(donationRecord);
                } 
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            else
            {
                return View(donationRecord);
            }
        }
        

        public IActionResult CreateEditDonorRecord(string? id)
        {
            donorRecord = new DonorRecord();
            if (id == null)
            {
                //Create New Record
                return View(donorRecord);
            }
            //Update by retriving infomation from DB
            donorRecord = _db.donorRecords.FirstOrDefault(u => u.dID == id);
            if (donorRecord == null)
            {
                return NotFound();
            }

            return View(donorRecord);
        }

        [HttpPost]
        public async Task<IActionResult> CreateEditDonorRecord(DonorRecord donorRecord)
        {
            if (ModelState.IsValid)
            {
                if (donorRecord.dID == null)
                {
                    //Create an Identity for the new Donor, based on the generated ID, assign the ID to the donor.dID
                    var user = new IdentityUser { UserName = donorRecord.username, Email = donorRecord.username };
                    var result = await _userManager.CreateAsync(user, donorRecord.password);
                    if (result.Succeeded)
                    {
                        donorRecord.dID = user.Id;
                        await _userManager.AddToRoleAsync(user, "Donor");
                        _db.donorRecords.Add(donorRecord);
                    }
                    
                }
                else
                {
                    //Update
                    _db.donorRecords.Update(donorRecord);
                    var user = await _userManager.FindByIdAsync(donorRecord.dID);
                    var result = await _userManager.SetUserNameAsync(user, donorRecord.username);
                    await _userManager.SetEmailAsync(user, donorRecord.username);
                    await _userManager.ChangePasswordAsync(user, user.PasswordHash, donorRecord.password);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            else
            {
                return View(donorRecord);
            }
        }

        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetDonorRecord()
        {
            return Json(new { data = await _db.donorRecords.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteDonorRecord(string id)
        {
            //await _db.donationRecords.AddAsync(donationRecord);
            var donorRecordDB = await _db.donorRecords.FirstOrDefaultAsync(u => u.dID == id);
            if (donorRecordDB == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            if (_db.donationRecords.Any(u => u.doneBy == id) == true)
            {
                return Json(new { success = false, message = "Donor has Donation Record" });
            }
            var user = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(user);
            _db.donorRecords.Remove(donorRecordDB);
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Delete Successful" });
        }

        [HttpGet]
        public async Task<IActionResult> GetDonationRecord()
        {
            return Json(new { data = await _db.donationRecords.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteDonationRecord(int id)
        {
            //await _db.donationRecords.AddAsync(donationRecord);
            var donationRecordDB = await _db.donationRecords.FirstOrDefaultAsync(u => u.dID == id);
            if (donationRecordDB == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            if (donationRecord.status == "Confirm")
            {
                return Json(new { success = false, message = "Donation has been confirmed" });
            }
            _db.donationRecords.Remove(donationRecordDB);
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Delete Successful" });
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDonationRecord(int id)
        {
            //await _db.donationRecords.AddAsync(donationRecord);
            var donationRecordDB = await _db.donationRecords.FirstOrDefaultAsync(u => u.dID == id);
            if (donationRecordDB == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            if (donationRecordDB.status == "Not Confirm")
            {
                donationRecordDB.status = "Confirm";
                _db.donationRecords.Update(donationRecordDB);
                await _db.SaveChangesAsync();

                return Json(new { success = true, message = "Confirm Successful" });
            }

            else
            {
                return Json(new { success = false, message = "Donation Status is already Confirm" });
            }
        }
        #endregion
    }
}

Views/Staff/CreateEditDonationRecord.cshtml
<!--Staff Donation Record-->
@model DonorProject.Models.DonationRecord

<h2 class="text-info">@(Model.dID!=0? "Edit":"Create")</h2>

<div class="border container" style="padding:30px">
    <form method="post">
        @if (Model.dID != 0)
        {
            <input type="hidden" asp-for="dID" />

        }
        <input type="hidden" asp-for="status" value="Not Confirm" />
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="name">Name / Company Name</label>
            </div>
            <div class="col-6">
                <input asp-for="name" class="form-control" />
            </div>
            <span asp-validation-for="name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="nric">NRIC / Company Registration Number</label>
            </div>
            <div class="col-6">
                <input asp-for="nric" class="form-control" />
            </div>
            <span asp-validation-for="nric" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="type"></label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio1">
                    <input type="radio" asp-for="type" value="Individual" class="form-check-inline" />Individual
                </label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="type" value="Company" class="form-check-inline" />Company
                </label>
            </div>
            <span asp-validation-for="type" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="address"></label>
            </div>
            <div class="col-6">
                <input asp-for="address" class="form-control" />
            </div>
            <span asp-validation-for="address" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="contactNo"></label>
            </div>
            <div class="col-6">
                <input asp-for="contactNo" class="form-control" />
            </div>
            <span asp-validation-for="contactNo" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="taxExemption"></label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio1">
                    <input type="radio" asp-for="taxExemption" value="Yes" class="form-check-inline" />Yes
                </label>
            </div>
            <div class="col-3">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="taxExemption" value="No" class="form-check-inline" />No
                </label>
            </div>
            <span asp-validation-for="taxExemption" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="dateOfDonation"></label>
            </div>
            <div class="col-6">
                <input asp-for="dateOfDonation" class="form-control" />
            </div>
            <span asp-validation-for="dateOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="amountOfDonation"></label>
            </div>
            <div class="col-6">
                <input asp-for="amountOfDonation" class="form-control" />
            </div>
            <span asp-validation-for="amountOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="receiptNo"></label>
            </div>
            <div class="col-6">
                <input asp-for="receiptNo" class="form-control" />
            </div>
            <span asp-validation-for="receiptNo" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="dateOfReceipt"></label>
            </div>
            <div class="col-6">
                <input asp-for="dateOfReceipt" class="form-control" />
            </div>
            <span asp-validation-for="dateOfReceipt" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="modeOfDonation"></label>
            </div>
            <div class="col-2">
                <label class="form-check-label" for="radio1">
                    <input type="radio" asp-for="modeOfDonation" value="cash" class="form-check-inline" />Cash
                </label>
            </div>
            <div class="col-2">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="modeOfDonation" value="cashcard" class="form-check-inline" />CashCard
                </label>
            </div>
            <div class="col-2">
                <label class="form-check-label" for="radio2">
                    <input type="radio" asp-for="modeOfDonation" value="mastercard" class="form-check-inline" />MasterCard
                </label>
            </div>
            <span asp-validation-for="modeOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="purposeOfDonation"></label>
            </div>
            <div class="col-6">
                <input asp-for="purposeOfDonation" class="form-control" />
            </div>
            <span asp-validation-for="purposeOfDonation" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="remarks"></label>
            </div>
            <div class="col-6">
                <textarea rows="5" asp-for="remarks" class="form-control"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.dID!=0? "Update":"Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back To Home Page</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Staff/CreateEditDonorRecord.cshtml
@model DonorProject.Models.DonorRecord

<h2 class="text-info">@(Model.dID!=null? "Edit":"Create") Donor Record</h2>

<div class="border container" style="padding:30px">
    <form method="post">
        @if (Model.dID != null)
        {
            <input type="hidden" asp-for="dID" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="name">Name</label>
            </div>
            <div class="col-6">
                <input asp-for="name" class="form-control" />
            </div>
            <span asp-validation-for="name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="nric">NRIC</label>
            </div>
            <div class="col-6">
                <input asp-for="nric" class="form-control" />
            </div>
            <span asp-validation-for="nric" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="address">Address</label>
            </div>
            <div class="col-6">
                <input asp-for="address" class="form-control" />
            </div>
            <span asp-validation-for="address" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="contactno">Contact Number</label>
            </div>
            <div class="col-6">
                <input asp-for="contactno" class="form-control" />
            </div>
            <span asp-validation-for="contactno" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="username">User Name</label>
            </div>
            <div class="col-6">
                <input asp-for="username" class="form-control" />
            </div>
            <span asp-validation-for="username" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="password">Password</label>
            </div>
            <div class="col-6">
                <input asp-for="password" class="form-control" />
            </div>
            <span asp-validation-for="password" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.dID!=null? "Update":"Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back To Home Page</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

Views/Staff/Index.cshtml
@{
    ViewData["Title"] = "Staff Home Page";
}

<div class="container row p-0 m-0">
    <div>
        <h2>Welcome to Staff Home Page</h2>
    </div>
    <div class="col-12 border p-3">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a asp-action="CreateEditDonorRecord" asp-controller="Staff" class="btn btn-info form-control text-white">
                    Add New Donor Record
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="ViewDonorRecord" asp-controller="Staff" class="btn btn-info form-control text-white">
                    View Donor Record
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="CreateEditDonationRecord" asp-controller="Staff" class="btn btn-info form-control text-white">
                    Add New Donation Record
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="ViewDonationRecord" asp-controller="Staff" class="btn btn-info form-control text-white">
                    View Donation Record
                </a>
            </li>
        </ul>
    </div>
</div>

Views/Staff/ViewDonationRecord.cshtml
@{
    ViewData["Title"] = "View Donation Record";
}

<div class="container row p-0 m-0">
    <div>
        View Donation Record
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style=" width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Date of Donation</th>
                    <th>Amount of Donation</th>
                    <th>Receipt Number</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/viewDonation.js"></script>
}

Views/Staff/ViewDonorRecord.cshtml
@{
    ViewData["Title"] = "View Donor Record";
}

<div class="container row p-0 m-0">
    <div>
        View Donor Record
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style=" width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Nric</th>
                    <th>Address</th>
                    <th>Contact No</th>
                    <th>User Name</th>
                    <th>Password</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/viewStaffDonor.js"></script>
}